/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFunctions;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.*;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ir4un
 */
public class QuantityMenu extends javax.swing.JFrame {

    /**
     * Creates new form startMenu
     */
    private int mousepX, mousepY;
    private Integer selectedQuantity, currentQuantity;
    private String retrievedProdID;
    private Double totalprice;
    final DecimalFormat moneyformat = new DecimalFormat("0.00");

    public QuantityMenu(String selectedProductID, int insertedQuantity) throws IOException {
        initComponents();
        this.retrievedProdID = selectedProductID;
        this.selectedQuantity = insertedQuantity;
        this.txtfproduct_desc.setLineWrap(true);
        this. txtfproduct_desc.setWrapStyleWord(true);
        retrieveData(selectedProductID);
        updateQuantity();
        setLogo();

    }

    private void setLogo() {
        String sourcefolder = System.getProperty("user.dir") + "\\src\\productthumbnail\\";
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(sourcefolder + "logo.png"));
        this.setTitle("PAWG Vending Machine");

    }

    private void retrieveData(String selectedProductID) throws IOException {
        String source = System.getProperty("user.dir");
        File file = new File(source + "\\src\\txtdatabase\\itemlist.txt");

        FileReader fr = new FileReader(file);
        BufferedReader br = new BufferedReader(fr);
        String record;
        int count = 1;

        while ((record = br.readLine()) != null) {

            String[] fields = record.split("::");
            String product_id = fields[0];
            String product_name = fields[1];
            String product_price = fields[2];
            String product_quantity = fields[3];
            String product_thumbslot = fields[4];
            String product_desc = fields[5];

            if (selectedProductID.equals(product_id)) { 
                lblproductslotdetail.setText("Slot: " + product_id);
                lblproduct_name.setText(product_name);
                lblproduct_price.setText("RM" + product_price);
                totalprice = Double.parseDouble(product_price);
                lblsetQuantity.setText(product_quantity);
                currentQuantity = Integer.parseInt(product_quantity);
                txtfproduct_desc.setText(product_desc);
                File thumbfile = new File(source + "\\src\\txtdatabase\\itemlist.txt");
                String thumbimg = source + "\\src\\productthumbnail\\" + product_thumbslot;
                ImageIcon imIco = new ImageIcon(thumbimg);
                Image imFit = imIco.getImage();
                Image imgScale = imFit.getScaledInstance(230, 230, Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(imgScale);
                lblproduct_thumb.setIcon(scaledIcon);
            } else {

            }
            setLabel(count, product_id, product_name, product_price, product_quantity, product_thumbslot);

            ++count;
        }
        br.close();

    }

    private void setLabel(int count, String product_id, String product_name, String product_price, String product_quantity, String product_thumbslot) {

        String source = System.getProperty("user.dir");

    }

    private void updateQuantity() {

        lblproduct_quantity.setText(selectedQuantity.toString());

    }

    private void addQuantity() {

        if (selectedQuantity >= currentQuantity) {
            JOptionPane.showMessageDialog(null, "You Have Selected The Maximum Amount! Sorry :p", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            selectedQuantity++;
            updateQuantity();
        }

    }

    private void subtractQuantity() {

        if (selectedQuantity <= 1) {
            JOptionPane.showMessageDialog(null, "You Need to Have At Least 1 Item To Purchase!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            selectedQuantity--;
            updateQuantity();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowsControl = new javax.swing.JPanel();
        windowsLogo = new javax.swing.JPanel();
        panellogo = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        windowsButtons1 = new javax.swing.JPanel();
        btnminmax = new javax.swing.JPanel();
        lblminmax = new javax.swing.JLabel();
        btnclose = new javax.swing.JPanel();
        lblclose = new javax.swing.JLabel();
        windowsButtons2 = new javax.swing.JPanel();
        paneltitle = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();
        pnlContent = new keeptoo.KGradientPanel();
        KbtnBack = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        pnlContent2 = new javax.swing.JPanel();
        pnlQuantity1 = new keeptoo.KGradientPanel();
        lbltitle1 = new javax.swing.JLabel();
        lblproduct_quantity = new javax.swing.JLabel();
        pnlPrice1 = new keeptoo.KGradientPanel();
        lblproduct_price = new javax.swing.JLabel();
        pnlSlot1 = new keeptoo.KGradientPanel();
        lblproductslotdetail = new javax.swing.JLabel();
        pnlName1 = new keeptoo.KGradientPanel();
        lblproduct_name = new javax.swing.JLabel();
        pnlThumb1 = new keeptoo.KGradientPanel();
        lblproduct_thumb = new javax.swing.JLabel();
        pnlBuy = new javax.swing.JPanel();
        pnlSlot2 = new keeptoo.KGradientPanel();
        lblitemtitle = new javax.swing.JLabel();
        pnlQuantity2 = new keeptoo.KGradientPanel();
        lbltitle2 = new javax.swing.JLabel();
        lblsetQuantity = new javax.swing.JLabel();
        txtfproduct_desc = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        KbtnLogin = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowsControl.setBackground(new java.awt.Color(51, 51, 51));
        windowsControl.setPreferredSize(new java.awt.Dimension(100, 50));
        windowsControl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowsControlMouseDragged(evt);
            }
        });
        windowsControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowsControlMousePressed(evt);
            }
        });
        windowsControl.setLayout(new java.awt.BorderLayout());

        windowsLogo.setBackground(new java.awt.Color(51, 51, 51));
        windowsLogo.setPreferredSize(new java.awt.Dimension(75, 50));

        panellogo.setBackground(new java.awt.Color(51, 51, 51));
        panellogo.setPreferredSize(new java.awt.Dimension(75, 50));
        panellogo.setLayout(new java.awt.BorderLayout());

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PAWG.png"))); // NOI18N
        lbllogo.setMaximumSize(new java.awt.Dimension(75, 50));
        lbllogo.setMinimumSize(new java.awt.Dimension(50, 50));
        lbllogo.setPreferredSize(new java.awt.Dimension(75, 50));
        lbllogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbllogoMouseDragged(evt);
            }
        });
        lbllogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllogoMousePressed(evt);
            }
        });
        panellogo.add(lbllogo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout windowsLogoLayout = new javax.swing.GroupLayout(windowsLogo);
        windowsLogo.setLayout(windowsLogoLayout);
        windowsLogoLayout.setHorizontalGroup(
            windowsLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowsLogoLayout.createSequentialGroup()
                .addComponent(panellogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        windowsLogoLayout.setVerticalGroup(
            windowsLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowsLogoLayout.createSequentialGroup()
                .addComponent(panellogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        windowsControl.add(windowsLogo, java.awt.BorderLayout.LINE_START);

        windowsButtons1.setBackground(new java.awt.Color(51, 51, 51));
        windowsButtons1.setPreferredSize(new java.awt.Dimension(200, 50));

        btnminmax.setBackground(new java.awt.Color(51, 51, 51));
        btnminmax.setLayout(new java.awt.BorderLayout());

        lblminmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblminmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minimize.png"))); // NOI18N
        lblminmax.setMaximumSize(new java.awt.Dimension(50, 50));
        lblminmax.setMinimumSize(new java.awt.Dimension(50, 50));
        lblminmax.setPreferredSize(new java.awt.Dimension(50, 50));
        lblminmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblminmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblminmaxMouseExited(evt);
            }
        });
        btnminmax.add(lblminmax, java.awt.BorderLayout.CENTER);

        btnclose.setBackground(new java.awt.Color(51, 51, 51));
        btnclose.setLayout(new java.awt.BorderLayout());

        lblclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/X.png"))); // NOI18N
        lblclose.setMaximumSize(new java.awt.Dimension(50, 50));
        lblclose.setMinimumSize(new java.awt.Dimension(50, 50));
        lblclose.setPreferredSize(new java.awt.Dimension(50, 50));
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcloseMouseExited(evt);
            }
        });
        btnclose.add(lblclose, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout windowsButtons1Layout = new javax.swing.GroupLayout(windowsButtons1);
        windowsButtons1.setLayout(windowsButtons1Layout);
        windowsButtons1Layout.setHorizontalGroup(
            windowsButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowsButtons1Layout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addComponent(btnminmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        windowsButtons1Layout.setVerticalGroup(
            windowsButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowsButtons1Layout.createSequentialGroup()
                .addGroup(windowsButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnminmax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        windowsControl.add(windowsButtons1, java.awt.BorderLayout.LINE_END);

        windowsButtons2.setBackground(new java.awt.Color(51, 51, 51));

        paneltitle.setBackground(new java.awt.Color(51, 51, 51));
        paneltitle.setLayout(new java.awt.BorderLayout());

        lbltitle.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Select Quantity");
        lbltitle.setMaximumSize(new java.awt.Dimension(500, 50));
        lbltitle.setMinimumSize(new java.awt.Dimension(50, 50));
        lbltitle.setPreferredSize(new java.awt.Dimension(500, 50));

        javax.swing.GroupLayout windowsButtons2Layout = new javax.swing.GroupLayout(windowsButtons2);
        windowsButtons2.setLayout(windowsButtons2Layout);
        windowsButtons2Layout.setHorizontalGroup(
            windowsButtons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, windowsButtons2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(paneltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        windowsButtons2Layout.setVerticalGroup(
            windowsButtons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(windowsButtons2Layout.createSequentialGroup()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        windowsControl.add(windowsButtons2, java.awt.BorderLayout.CENTER);

        getContentPane().add(windowsControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pnlContent.setkBorderRadius(0);
        pnlContent.setkEndColor(new java.awt.Color(28, 167, 236));
        pnlContent.setkStartColor(new java.awt.Color(31, 47, 152));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KbtnBack.setText("Back");
        KbtnBack.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        KbtnBack.setkEndColor(new java.awt.Color(255, 51, 255));
        KbtnBack.setkHoverEndColor(new java.awt.Color(204, 0, 0));
        KbtnBack.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        KbtnBack.setkHoverStartColor(new java.awt.Color(204, 0, 204));
        KbtnBack.setkPressedColor(new java.awt.Color(153, 0, 51));
        KbtnBack.setkStartColor(new java.awt.Color(204, 0, 0));
        KbtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KbtnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KbtnBackMouseExited(evt);
            }
        });
        KbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbtnBackActionPerformed(evt);
            }
        });
        pnlContent.add(KbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Set The Quantity of The Item To Be Purchased");
        pnlContent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        pnlContent2.setBackground(new java.awt.Color(51, 51, 51));
        pnlContent2.setLayout(null);

        pnlQuantity1.setkBorderRadius(0);
        pnlQuantity1.setkEndColor(new java.awt.Color(0, 153, 51));
        pnlQuantity1.setkStartColor(new java.awt.Color(0, 102, 102));
        pnlQuantity1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbltitle1.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle1.setText("Quantity Selected:");
        pnlQuantity1.add(lbltitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 175, 40));

        lblproduct_quantity.setBackground(new java.awt.Color(51, 51, 51));
        lblproduct_quantity.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblproduct_quantity.setForeground(new java.awt.Color(255, 255, 255));
        lblproduct_quantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproduct_quantity.setText("000");
        pnlQuantity1.add(lblproduct_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 40, 180, 82));

        pnlContent2.add(pnlQuantity1);
        pnlQuantity1.setBounds(460, 240, 180, 130);

        pnlPrice1.setkBorderRadius(0);
        pnlPrice1.setkEndColor(new java.awt.Color(153, 0, 153));
        pnlPrice1.setkStartColor(new java.awt.Color(102, 0, 102));

        lblproduct_price.setBackground(new java.awt.Color(102, 0, 102));
        lblproduct_price.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        lblproduct_price.setForeground(new java.awt.Color(204, 204, 204));
        lblproduct_price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproduct_price.setText("RM000.00");

        javax.swing.GroupLayout pnlPrice1Layout = new javax.swing.GroupLayout(pnlPrice1);
        pnlPrice1.setLayout(pnlPrice1Layout);
        pnlPrice1Layout.setHorizontalGroup(
            pnlPrice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproduct_price, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        pnlPrice1Layout.setVerticalGroup(
            pnlPrice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproduct_price, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        pnlContent2.add(pnlPrice1);
        pnlPrice1.setBounds(0, 280, 280, 90);

        pnlSlot1.setkBorderRadius(0);
        pnlSlot1.setkEndColor(new java.awt.Color(31, 47, 152));
        pnlSlot1.setkGradientFocus(1000);
        pnlSlot1.setkStartColor(new java.awt.Color(31, 47, 152));

        lblproductslotdetail.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        lblproductslotdetail.setForeground(new java.awt.Color(255, 255, 255));
        lblproductslotdetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproductslotdetail.setText("Slot: 000");

        javax.swing.GroupLayout pnlSlot1Layout = new javax.swing.GroupLayout(pnlSlot1);
        pnlSlot1.setLayout(pnlSlot1Layout);
        pnlSlot1Layout.setHorizontalGroup(
            pnlSlot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproductslotdetail, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlSlot1Layout.setVerticalGroup(
            pnlSlot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlot1Layout.createSequentialGroup()
                .addComponent(lblproductslotdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pnlContent2.add(pnlSlot1);
        pnlSlot1.setBounds(280, 60, 140, 60);

        pnlName1.setkBorderRadius(0);
        pnlName1.setkEndColor(new java.awt.Color(102, 102, 102));
        pnlName1.setkStartColor(new java.awt.Color(153, 153, 153));
        pnlName1.setkTransparentControls(false);

        lblproduct_name.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblproduct_name.setForeground(new java.awt.Color(255, 255, 255));
        lblproduct_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproduct_name.setText("Item Name");

        javax.swing.GroupLayout pnlName1Layout = new javax.swing.GroupLayout(pnlName1);
        pnlName1.setLayout(pnlName1Layout);
        pnlName1Layout.setHorizontalGroup(
            pnlName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproduct_name, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        pnlName1Layout.setVerticalGroup(
            pnlName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblproduct_name, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlContent2.add(pnlName1);
        pnlName1.setBounds(420, 60, 540, 60);

        pnlThumb1.setkBorderRadius(0);
        pnlThumb1.setkEndColor(new java.awt.Color(51, 51, 51));
        pnlThumb1.setkStartColor(new java.awt.Color(204, 204, 204));

        lblproduct_thumb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblproduct_thumb.setMaximumSize(new java.awt.Dimension(415, 415));
        lblproduct_thumb.setMinimumSize(new java.awt.Dimension(415, 415));
        lblproduct_thumb.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout pnlThumb1Layout = new javax.swing.GroupLayout(pnlThumb1);
        pnlThumb1.setLayout(pnlThumb1Layout);
        pnlThumb1Layout.setHorizontalGroup(
            pnlThumb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThumb1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblproduct_thumb, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlThumb1Layout.setVerticalGroup(
            pnlThumb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThumb1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblproduct_thumb, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pnlContent2.add(pnlThumb1);
        pnlThumb1.setBounds(0, 0, 280, 280);

        pnlBuy.setBackground(new java.awt.Color(51, 51, 51));
        pnlBuy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlContent2.add(pnlBuy);
        pnlBuy.setBounds(280, 280, 220, 0);

        pnlSlot2.setkBorderRadius(0);
        pnlSlot2.setkEndColor(new java.awt.Color(51, 51, 51));
        pnlSlot2.setkGradientFocus(1000);
        pnlSlot2.setkStartColor(new java.awt.Color(51, 51, 51));

        lblitemtitle.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblitemtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblitemtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblitemtitle.setText("Details");

        javax.swing.GroupLayout pnlSlot2Layout = new javax.swing.GroupLayout(pnlSlot2);
        pnlSlot2.setLayout(pnlSlot2Layout);
        pnlSlot2Layout.setHorizontalGroup(
            pnlSlot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblitemtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        pnlSlot2Layout.setVerticalGroup(
            pnlSlot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlot2Layout.createSequentialGroup()
                .addComponent(lblitemtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pnlContent2.add(pnlSlot2);
        pnlSlot2.setBounds(280, 0, 680, 60);

        pnlQuantity2.setkBorderRadius(0);
        pnlQuantity2.setkStartColor(new java.awt.Color(123, 213, 245));
        pnlQuantity2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbltitle2.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle2.setText("Quantity Available:");
        pnlQuantity2.add(lbltitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 175, 40));

        lblsetQuantity.setBackground(new java.awt.Color(51, 51, 51));
        lblsetQuantity.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblsetQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblsetQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsetQuantity.setText("000");
        pnlQuantity2.add(lblsetQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 82));

        pnlContent2.add(pnlQuantity2);
        pnlQuantity2.setBounds(280, 240, 180, 130);

        txtfproduct_desc.setEditable(false);
        txtfproduct_desc.setBackground(new java.awt.Color(102, 102, 102));
        txtfproduct_desc.setColumns(20);
        txtfproduct_desc.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        txtfproduct_desc.setForeground(new java.awt.Color(255, 255, 255));
        txtfproduct_desc.setRows(3);
        txtfproduct_desc.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(102, 102, 102)));
        txtfproduct_desc.setFocusable(false);
        pnlContent2.add(txtfproduct_desc);
        txtfproduct_desc.setBounds(280, 120, 680, 120);

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addsmol.png"))); // NOI18N
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlContent2.add(btnAdd);
        btnAdd.setBounds(630, 230, 170, 150);

        btnSub.setBackground(new java.awt.Color(116, 12, 33));
        btnSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sub.png"))); // NOI18N
        btnSub.setBorderPainted(false);
        btnSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        pnlContent2.add(btnSub);
        btnSub.setBounds(790, 230, 180, 150);

        pnlContent.add(pnlContent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 960, 370));

        KbtnLogin.setText("Proceed To Payment");
        KbtnLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        KbtnLogin.setkEndColor(new java.awt.Color(25, 128, 179));
        KbtnLogin.setkHoverEndColor(new java.awt.Color(31, 47, 152));
        KbtnLogin.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        KbtnLogin.setkHoverStartColor(new java.awt.Color(28, 167, 236));
        KbtnLogin.setkPressedColor(new java.awt.Color(0, 102, 204));
        KbtnLogin.setkStartColor(new java.awt.Color(31, 47, 152));
        KbtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KbtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KbtnLoginMouseExited(evt);
            }
        });
        KbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbtnLoginActionPerformed(evt);
            }
        });
        pnlContent.add(KbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 260, 60));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1030, 550));

        setSize(new java.awt.Dimension(1024, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);

    }
    private void windowsControlMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowsControlMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();

        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
    }//GEN-LAST:event_windowsControlMouseDragged

    private void windowsControlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowsControlMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_windowsControlMousePressed

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblcloseMouseClicked

    private void lblcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseEntered
        changecolor(btnclose, new Color(93, 93, 93));
        lblclose.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));    }//GEN-LAST:event_lblcloseMouseEntered

    private void lblcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseExited
        changecolor(btnclose, new Color(51, 51, 51));
        lblclose.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));    }//GEN-LAST:event_lblcloseMouseExited

    private void lbllogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();    }//GEN-LAST:event_lbllogoMousePressed

    private void lbllogoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();

        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);    }//GEN-LAST:event_lbllogoMouseDragged

    private void lblminmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminmaxMouseEntered
        changecolor(btnminmax, new Color(93, 93, 93));
        lblminmax.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));    }//GEN-LAST:event_lblminmaxMouseEntered

    private void lblminmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminmaxMouseExited
        changecolor(btnminmax, new Color(51, 51, 51));
        lblminmax.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));    }//GEN-LAST:event_lblminmaxMouseExited

    private void lblminmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminmaxMouseClicked
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lblminmaxMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addQuantity();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        subtractQuantity();
    }//GEN-LAST:event_btnSubActionPerformed

    private void KbtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KbtnBackMouseEntered
        KbtnBack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_KbtnBackMouseEntered

    private void KbtnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KbtnBackMouseExited
        KbtnBack.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_KbtnBackMouseExited

    private void KbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbtnBackActionPerformed

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Go Back? \n Inserted Information Will Not be Saved!", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {

            try {
                MainMenu mmenu;
                mmenu = new MainMenu();
                mmenu.setVisible(true);
                dispose();

            } catch (IOException ex) {
            }
        } else {

        }


    }//GEN-LAST:event_KbtnBackActionPerformed

    private void KbtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KbtnLoginMouseEntered
        KbtnLogin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_KbtnLoginMouseEntered

    private void KbtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KbtnLoginMouseExited
        KbtnLogin.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_KbtnLoginMouseExited

    private void KbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbtnLoginActionPerformed
        try {

            totalprice = totalprice * selectedQuantity;
            moneyformat.format(totalprice);

            new PaymentMenu(retrievedProdID, selectedQuantity, totalprice).setVisible(true);
            dispose();

        } catch (IOException ex) {
            JOptionPane.showConfirmDialog(null, "An Error Occured!");
        }
    }//GEN-LAST:event_KbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuantityMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuantityMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuantityMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuantityMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    private javax.swing.JLabel displaytext;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton KbtnBack;
    private keeptoo.KButton KbtnLogin;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSub;
    private javax.swing.JPanel btnclose;
    private javax.swing.JPanel btnminmax;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblitemtitle;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblminmax;
    private javax.swing.JLabel lblproduct_name;
    private javax.swing.JLabel lblproduct_price;
    private javax.swing.JLabel lblproduct_quantity;
    private javax.swing.JLabel lblproduct_thumb;
    private javax.swing.JLabel lblproductslotdetail;
    private javax.swing.JLabel lblsetQuantity;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lbltitle2;
    private javax.swing.JPanel panellogo;
    private javax.swing.JPanel paneltitle;
    private javax.swing.JPanel pnlBuy;
    private keeptoo.KGradientPanel pnlContent;
    private javax.swing.JPanel pnlContent2;
    private keeptoo.KGradientPanel pnlName1;
    private keeptoo.KGradientPanel pnlPrice1;
    private keeptoo.KGradientPanel pnlQuantity1;
    private keeptoo.KGradientPanel pnlQuantity2;
    private keeptoo.KGradientPanel pnlSlot1;
    private keeptoo.KGradientPanel pnlSlot2;
    private keeptoo.KGradientPanel pnlThumb1;
    private javax.swing.JTextArea txtfproduct_desc;
    private javax.swing.JPanel windowsButtons1;
    private javax.swing.JPanel windowsButtons2;
    private javax.swing.JPanel windowsControl;
    private javax.swing.JPanel windowsLogo;
    // End of variables declaration//GEN-END:variables
}
